### ISSUE TITLE
evaluator文件夹里的ppl_yelp.binary和acc_yelp.bin

### ISSUE THREAD

**Issue by czhxiaohuihui** [fastnlp/style-transformer#1]
您好，
在运行的时候，发生了错误，evaluator/acc_yelp.bin has wrong file format!

然后，您能不能更详细地说明一下如何生成这两个文件，非常感谢！！！

**Comment by ohlionel** [comment]
你可以使用fasttext和yelp的训练集训练一个二分类器：
```
import fasttext 
classifier = fasttext.supervised('yelp.train', 'acc_yelp')
result = classifier.test('yelp.valid')
print ('P@1:', result.precision)
print ('R@1:', result.recall)
print ('Number of examples:', result.nexamples)
```
然后使用kenlm，把yelp的训练集当训练语料，训练一个语言模型，可以参考：
https://kheafield.com/code/kenlm/
https://www.cnblogs.com/Climbing-Snail/p/9519079.html

**Comment by adamsZQ** [comment]
你好，我运行的时候也出现了这个错误，主要原因是最新版的fasttext更改了模型的结构，所以只需要将fasttext降低到0.8.x即可
